starting test execution
cancel_func.cpp(6) critical assertion failed [expression]: false
cancel_func.cpp(6) report: continuing in main: { executed : 1, warnings : 0, errors : 1}
cancel_func.cpp(12) expectation failed [expression]: false
free tests : { executed : 2, warnings : 1, errors : 1}
full test report: { executed : 2, warnings : 1, errors : 1}